source 'https://rubygems.org'
ruby   '2.3.1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.13'

# Services
gem 'pg'
gem 'puma'

# Assets
gem 'sass-rails',                    '~> 4.0.2'
gem 'uglifier',                      '>= 1.3.0'
gem 'coffee-rails',                  '~> 4.0.0'
gem 'jquery-rails'
gem 'haml-rails'
gem 'bootstrap-sass',                '~> 3.3.5'
gem 'font-awesome-rails',            '~> 4.6.3.1'
gem 'swiper-rails',                  '~> 1.0.4'
gem 'masonry-rails',                 '~> 0.2.4'

# Utils
gem 'activerecord-humanized_errors', '~> 2.0.1'
gem 'awesome_print',                 '~> 1.6.1'
gem 'ffaker',                        '~> 2.2.0'
gem 'route_translator',              '~> 4.4.1'

group :development, :test do
  gem 'capybara',         '~> 2.4.4'
  gem 'capybara-webkit',  '~> 1.4.1'
  gem 'fabrication',      '~> 2.12.2'
  gem 'pry-byebug',       '~> 3.3.0'
  gem 'rspec-rails',      '~> 3.2.1'
  gem 'rails-erd',        '~> 1.5.0'
end

group :production do
  gem 'rails_12factor',   '~> 0.0.3'
end
